name: Python Django Coverage GitHub Action
inputs:
  django-app:
    description: "Application"
    required: false
    default: ""
  minimum-coverage:
    description: "Minimum allowed code coverage"
    required: false
    default: "10"  
  requirements-file:
    description: "Path to requirements file"
    required: false
    default: "requirements.txt"  
  db-name:
    description: "Name of the test database"
    required: false
    default: "demo"  
  db-user:
    description: "Name of user to access the test database"
    required: false
    default: "ctest"  
  db-pass:
    description: "Password of user to access the test database"
    required: false
    default: "coveragetest123"  
description: 'Github Action to run tests and get coverage with Django on a Python Docker image'
branding:
  icon: box
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.django-app }}
  - ${{ inputs.minimum-coverage }}
  - ${{ inputs.requirements-file }}
  - ${{ inputs.db-name }}
  - ${{ inputs.db-user }}
  - ${{ inputs.db-pass }}
